import { useMemo, useState } from 'react';
import { Activity, Bot, Check, ChevronRight, Clock3, MessageCircle, Send, Sparkles, Users, X } from 'lucide-react';
import { addComment, getDocumentVersion, resolveComment } from '../../services/advancedService';
import { getSocket } from '../../services/socketService';

function formatTime(value){return new Intl.DateTimeFormat(undefined,{hour:'2-digit',minute:'2-digit',day:'2-digit',month:'short'}).format(new Date(value));}
export default function AdvancedPanel({mode,onClose,documentId,objects,comments,setComments,versions,setVersions,workspace,members,activities,onRestore}){
 const [comment,setComment]=useState(''); const [busy,setBusy]=useState(false);
 const selectedObjectId=mode.objectId;
 const linkedComments=useMemo(()=>comments.filter(c=>!c.resolved && (!selectedObjectId || c.object_id===selectedObjectId)),[comments,selectedObjectId]);
 const summary=useMemo(()=>{const types={};objects.forEach(o=>types[o.type]=(types[o.type]||0)+1);const text=objects.filter(o=>o.text).map(o=>o.text).filter(Boolean);return {types,text};},[objects]);
 const post=async()=>{if(!comment.trim())return;setBusy(true);try{const r=await addComment(documentId,{body:comment,objectId:selectedObjectId||null});setComments(c=>[r.comment,...c]);getSocket()?.emit('document:comment-added',{workspaceId:workspace.id,comment:r.comment});setComment('');}finally{setBusy(false)}};
 const restore=async(id)=>{setBusy(true);try{const r=await getDocumentVersion(documentId,id);if(r.version?.content?.objects)onRestore(r.version.content.objects);}finally{setBusy(false)}};
 const resolve=async id=>{await resolveComment(id);setComments(c=>c.map(x=>x.id===id?{...x,resolved:true}:x));getSocket()?.emit('document:comment-resolved',{workspaceId:workspace.id,commentId:id});};
 return <aside className="cc-advanced-panel"><div className="cc-advanced-head"><div><span className="cc-advanced-kicker">Workspace intelligence</span><h3>{mode.type==='comments'?'Comments':mode.type==='history'?'Time Machine':mode.type==='copilot'?'Canvas Copilot':'Live Activity'}</h3></div><button onClick={onClose}><X size={17}/></button></div>
 {mode.type==='comments'&&<div className="cc-advanced-content"><div className="cc-panel-context"><MessageCircle size={16}/><span>{selectedObjectId?'Comments on selected object':'All unresolved comments'}</span></div><div className="cc-comment-list">{linkedComments.length?linkedComments.map(c=><div className="cc-comment" key={c.id}><div className="cc-comment-avatar">{c.user_name?.[0]?.toUpperCase()}</div><div className="cc-comment-body"><div><strong>{c.user_name}</strong><time>{formatTime(c.created_at)}</time></div><p>{c.body}</p><button onClick={()=>resolve(c.id)}><Check size={13}/>Resolve</button></div></div>):<div className="cc-empty-panel"><MessageCircle size={28}/><strong>No unresolved comments</strong><span>Start a discussion from the selected canvas object.</span></div>}</div><div className="cc-comment-compose"><textarea value={comment} onChange={e=>setComment(e.target.value)} placeholder="Write a comment…"/><button disabled={busy||!comment.trim()} onClick={post}><Send size={15}/></button></div></div>}
 {mode.type==='history'&&<div className="cc-advanced-content"><div className="cc-panel-context"><Clock3 size={16}/><span>Every saved canvas state becomes a restore point.</span></div><div className="cc-history-list">{versions.length?versions.map(v=><button key={v.id} onClick={()=>restore(v.id)} disabled={busy}><span className="cc-history-number">v{v.version_number}</span><span><strong>Version {v.version_number}</strong><small>{v.user_name} · {formatTime(v.created_at)}</small></span><ChevronRight size={15}/></button>):<div className="cc-empty-panel"><Clock3 size={28}/><strong>No versions yet</strong><span>Make an edit and save it to create the first snapshot.</span></div>}</div></div>}
 {mode.type==='copilot'&&<div className="cc-advanced-content"><div className="cc-copilot-hero"><div className="cc-copilot-orb"><Sparkles size={23}/></div><div><strong>Canvas Copilot</strong><span>Local analysis of your live board</span></div></div><div className="cc-insight-grid"><div><strong>{objects.length}</strong><span>Objects</span></div><div><strong>{members.length}</strong><span>Members</span></div><div><strong>{comments.filter(c=>!c.resolved).length}</strong><span>Open threads</span></div></div><div className="cc-analysis"><h4>Board briefing</h4><p>{objects.length===0?'Your board is empty. Start with a sticky note or diagram.':`This board contains ${objects.length} objects across ${Object.keys(summary.types).length} object types. ${summary.text.length?`Text content detected: “${summary.text.slice(0,3).join(' · ')}”.`:'Add text or sticky notes to give the board more semantic context.'}`}</p></div><div className="cc-suggestions"><span>Suggested next steps</span><div>{objects.some(o=>o.type==='sticky')&&<button>Convert stickies into tasks <ChevronRight size={14}/></button>}<button>Review unresolved comments <ChevronRight size={14}/></button><button>Open collaboration history <ChevronRight size={14}/></button></div></div></div>}
 {mode.type==='activity'&&<div className="cc-advanced-content"><div className="cc-panel-context"><Activity size={16}/><span>Live events from this workspace</span></div><div className="cc-activity-list">{activities.length?activities.map((a,i)=><div key={a.id||i}><span className="cc-activity-dot"/><div><strong>{a.user_name||'Collaborator'}</strong><p>{a.action}</p><small>{formatTime(a.created_at)}</small></div></div>):<div className="cc-empty-panel"><Activity size={28}/><strong>No activity yet</strong><span>Your workspace activity will appear here.</span></div>}</div></div>}
 </aside>
}
