import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import { Activity, ArrowLeft, Bot, Check, ChevronDown, Cloud, Command, Copy, Download, History, LoaderCircle, MessageCircle, MoreHorizontal, Pencil, Share2, Users, Wifi, WifiOff } from 'lucide-react';
import useAuth from '../../hooks/useAuth';
import { getSocket } from '../../services/socketService';
import { createWorkspaceDocument, getWorkspaceDocument, renameDocument, updateDocument } from '../../services/documentService';
import { getWorkspace, getWorkspaceActivity, getWorkspaceMembers } from '../../services/workspaceService';
import { getComments, getDocumentVersions } from '../../services/advancedService';
import Canvas from '../../components/canvas/Canvas';
import CanvasToolbar from '../../components/canvas/CanvasToolbar';
import PresenceBar from '../../components/canvas/PresenceBar';
import CursorLayer from '../../components/canvas/CursorLayer';
import PropertiesPanel from '../../components/canvas/PropertiesPanel';
import Modal from '../../components/common/Modal';
import Loader from '../../components/common/Loader';
import CommandPalette from '../../components/advanced/CommandPalette';
import MiniMap from '../../components/advanced/MiniMap';
import AdvancedPanel from '../../components/advanced/AdvancedPanel';
import './Workspace.css';

const clone=v=>JSON.parse(JSON.stringify(v));

export default function Workspace(){
 const {workspaceId}=useParams(); const {user}=useAuth();
 const [workspace,setWorkspace]=useState(null),[document,setDocument]=useState(null),[objects,setObjects]=useState([]),[selectedObjectId,setSelectedObjectId]=useState(null);
 const [members,setMembers]=useState([]),[activities,setActivities]=useState([]),[comments,setComments]=useState([]),[versions,setVersions]=useState([]);
 const [socket,setSocket]=useState(null),[onlineUsers,setOnlineUsers]=useState([]),[remoteCursors,setRemoteCursors]=useState({});
 const [activeTool,setActiveTool]=useState('select'),[zoom,setZoom]=useState(1),[gridEnabled,setGridEnabled]=useState(true),[snapEnabled,setSnapEnabled]=useState(true);
 const [saveStatus,setSaveStatus]=useState('Loading'),[loadError,setLoadError]=useState(''),[title,setTitle]=useState('Untitled Canvas'),[editingTitle,setEditingTitle]=useState(false);
 const [panel,setPanel]=useState(null),[commandOpen,setCommandOpen]=useState(false),[membersOpen,setMembersOpen]=useState(false),[shareOpen,setShareOpen]=useState(false);
 const historyRef=useRef([[]]),historyIndexRef=useRef(0),saveTimer=useRef(null),loadedRef=useRef(false),skipHistory=useRef(false);
 const selectedObject=useMemo(()=>objects.find(o=>o.id===selectedObjectId)||null,[objects,selectedObjectId]);

 const pushHistory=useCallback(next=>{if(skipHistory.current)return;const i=historyIndexRef.current;const nextHistory=historyRef.current.slice(0,i+1);nextHistory.push(clone(next));if(nextHistory.length>60)nextHistory.shift();historyRef.current=nextHistory;historyIndexRef.current=nextHistory.length-1;},[]);
 const persist=useCallback(next=>{if(!document?.id||!loadedRef.current)return;clearTimeout(saveTimer.current);setSaveStatus('Saving…');saveTimer.current=setTimeout(async()=>{try{const r=await updateDocument(document.id,{objects:next});setDocument(r.document);setSaveStatus('Saved');const v=await getDocumentVersions(document.id);setVersions(v.versions||[]);}catch(e){console.error(e);setSaveStatus('Save failed');}},500);},[document?.id]);
 const commit=useCallback(next=>{setObjects(next);pushHistory(next);persist(next);},[persist,pushHistory]);

 useEffect(()=>{let cancelled=false;(async()=>{try{setSaveStatus('Loading');const [w,d,m,a]=await Promise.all([getWorkspace(workspaceId),getWorkspaceDocument(workspaceId),getWorkspaceMembers(workspaceId),getWorkspaceActivity(workspaceId)]);if(cancelled)return;setWorkspace(w.workspace);setMembers(m.members||[]);setActivities(a.activities||[]);let doc=d.document;if(!doc)doc=(await createWorkspaceDocument(workspaceId,{title:'Untitled Canvas',content:{objects:[]}})).document;setDocument(doc);setTitle(doc.title||'Untitled Canvas');const initial=Array.isArray(doc.content?.objects)?doc.content.objects:[];setObjects(initial);historyRef.current=[clone(initial)];historyIndexRef.current=0;loadedRef.current=true;setComments((await getComments(doc.id)).comments||[]);setVersions((await getDocumentVersions(doc.id)).versions||[]);setSaveStatus('Saved');}catch(e){setLoadError(e.response?.data?.message||'Unable to load this workspace.');setSaveStatus('Error');}})();return()=>{cancelled=true;clearTimeout(saveTimer.current);loadedRef.current=false;};},[workspaceId]);

 useEffect(()=>{if(!user||!workspaceId)return;const s=getSocket();if(!s){setSaveStatus('Offline');return;}setSocket(s);const join=()=>s.emit('workspace:join',workspaceId);if(s.connected)join();else s.once('connect',join);
  const users=u=>setOnlineUsers(u||[]),joined=d=>d?.user&&setOnlineUsers(c=>c.some(x=>x.socketId===d.socketId)?c:[...c,{socketId:d.socketId,userId:d.user.id,id:d.user.id,name:d.user.name,email:d.user.email}]),left=d=>{setOnlineUsers(c=>c.filter(x=>x.socketId!==d?.socketId));if(d?.socketId)setRemoteCursors(c=>{const n={...c};delete n[d.socketId];return n;});},cursor=d=>d?.socketId&&setRemoteCursors(c=>({...c,[d.socketId]:d}));
  const created=d=>d?.object&&setObjects(c=>c.some(o=>o.id===d.object.id)?c:[...c,d.object]),updated=d=>d?.object&&setObjects(c=>c.map(o=>o.id===d.object.id?{...o,...d.object}:o)),deleted=d=>{if(!d?.objectId)return;setObjects(c=>c.filter(o=>o.id!==d.objectId));setSelectedObjectId(id=>id===d.objectId?null:id)};
  const commentAdded=c=>c?.id&&setComments(prev=>prev.some(x=>x.id===c.id)?prev:[c,...prev]);const commentResolved=d=>setComments(c=>c.map(x=>x.id===d.commentId?{...x,resolved:true}:x));const activity=a=>a&&setActivities(c=>[a,...c].slice(0,50));
  s.on('workspace:users',users);s.on('presence:user-joined',joined);s.on('presence:user-left',left);s.on('cursor:moved',cursor);s.on('canvas:object-created',created);s.on('canvas:object-updated',updated);s.on('canvas:object-deleted',deleted);s.on('document:comment-added',commentAdded);s.on('document:comment-resolved',commentResolved);s.on('workspace:activity',activity);s.on('connect',()=>{setSaveStatus('Saved');join()});s.on('disconnect',()=>setSaveStatus('Offline'));
  return()=>{['workspace:users','presence:user-joined','presence:user-left','cursor:moved','canvas:object-created','canvas:object-updated','canvas:object-deleted','document:comment-added','document:comment-resolved','workspace:activity'].forEach(ev=>s.off(ev));s.off('connect');s.off('disconnect');s.emit('workspace:leave',workspaceId);};
 },[workspaceId,user]);

 const emit=(event,payload)=>socket?.connected&&socket.emit(event,{workspaceId,...payload});
 const handleCreate=o=>{const next=[...objects,o];commit(next);setSelectedObjectId(o.id);emit('canvas:object-created',{object:o});};
 const handleMove=(id,pos)=>{const next=objects.map(o=>o.id===id?{...o,...pos}:o);commit(next);emit('canvas:object-updated',{object:{id,...pos}});};
 const handleChange=(id,changes)=>{const next=objects.map(o=>o.id===id?{...o,...changes}:o);commit(next);emit('canvas:object-updated',{object:{id,...changes}});};
 const handleDelete=()=>{if(!selectedObjectId)return;const next=objects.filter(o=>o.id!==selectedObjectId);commit(next);emit('canvas:object-deleted',{objectId:selectedObjectId});setSelectedObjectId(null);};
 const handleDuplicate=()=>{if(!selectedObject)return;const duplicate={...clone(selectedObject),id:crypto.randomUUID(),x:(selectedObject.x||0)+30,y:(selectedObject.y||0)+30};const next=[...objects,duplicate];commit(next);emit('canvas:object-created',{object:duplicate});setSelectedObjectId(duplicate.id);};
 const undo=()=>{const i=historyIndexRef.current;if(i<=0)return;const next=clone(historyRef.current[i-1]);historyIndexRef.current=i-1;skipHistory.current=true;setObjects(next);skipHistory.current=false;persist(next);};
 const redo=()=>{const i=historyIndexRef.current;if(i>=historyRef.current.length-1)return;const next=clone(historyRef.current[i+1]);historyIndexRef.current=i+1;skipHistory.current=true;setObjects(next);skipHistory.current=false;persist(next);};
 const handleRestore=next=>{commit(clone(next));setPanel(null);};
 const exportBoard=()=>{const blob=new Blob([JSON.stringify({workspace:workspace?.name,document:title,objects},null,2)],{type:'application/json'});const a=globalThis.document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`${title.replace(/[^a-z0-9]+/gi,'-').toLowerCase()||'canvas'}.json`;a.click();URL.revokeObjectURL(a.href);};
 const commandAction=id=>({select:()=>setActiveTool('select'),sticky:()=>setActiveTool('sticky'),text:()=>setActiveTool('text'),history:()=>setPanel({type:'history'}),comments:()=>setPanel({type:'comments',objectId:selectedObjectId}),copilot:()=>setPanel({type:'copilot'}),grid:()=>setGridEnabled(v=>!v),zoom:()=>setZoom(1),export:exportBoard}[id]?.());
 useEffect(()=>{const fn=e=>{const typing=['INPUT','TEXTAREA'].includes(e.target?.tagName)||e.target?.isContentEditable;if(typing)return;if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();setCommandOpen(v=>!v);return;}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='z'){e.preventDefault();e.shiftKey?redo():undo();return;}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='y'){e.preventDefault();redo();return;}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='d'){e.preventDefault();handleDuplicate();return;}if(e.key==='Delete'||e.key==='Backspace'){e.preventDefault();handleDelete();return;}const key=e.key.toLowerCase();if(!e.ctrlKey&&!e.metaKey){({v:()=>setActiveTool('select'),t:()=>setActiveTool('text'),r:()=>setActiveTool('rectangle'),s:()=>setActiveTool('sticky'),l:()=>setActiveTool('connector'),p:()=>setActiveTool('draw')})[key]?.();}};window.addEventListener('keydown',fn);return()=>window.removeEventListener('keydown',fn);});
 const cursorMove=p=>emit('cursor:move',p);
 const saveTitle=async()=>{const next=title.trim()||'Untitled Canvas';setTitle(next);setEditingTitle(false);if(document?.id){try{const r=await renameDocument(document.id,next);setDocument(r.document);}catch{setTitle(document.title)}}};
 const share=async()=>{try{await navigator.clipboard.writeText(window.location.href);}finally{setShareOpen(true);setTimeout(()=>setShareOpen(false),1600)}};
 const addCommentPanel=()=>setPanel({type:'comments',objectId:selectedObjectId});
 if(loadError)return <div className="workspace-error"><Link to="/dashboard"><ArrowLeft size={16}/>Back to dashboard</Link><h1>Workspace unavailable</h1><p>{loadError}</p></div>;
 if(!workspace||!document)return <div className="workspace-loading"><Loader label="Opening your workspace…"/></div>;
 return <div className="workspace-page">
  <header className="workspace-topbar"><div className="workspace-left"><Link to="/dashboard" className="workspace-back"><ArrowLeft size={18}/></Link><div className="workspace-title">{editingTitle?<input autoFocus value={title} onChange={e=>setTitle(e.target.value)} onBlur={saveTitle} onKeyDown={e=>e.key==='Enter'&&saveTitle()}/>:<button onDoubleClick={()=>setEditingTitle(true)} title="Double-click to rename"><h1>{title}</h1><Pencil size={13}/></button>}<span>{workspace.name}</span></div></div><div className="workspace-right"><button className="cc-command-trigger" onClick={()=>setCommandOpen(true)}><Command size={14}/><span>Quick actions</span><kbd>Ctrl K</kbd></button><div className={`workspace-connection ${socket?.connected?'online':'offline'}`}>{socket?.connected?<Wifi size={14}/>:<WifiOff size={14}/>}<span>{socket?.connected?'Live':'Offline'}</span></div><div className="workspace-save-status">{saveStatus==='Saving…'?<LoaderCircle size={14} className="spin"/>:saveStatus==='Saved'?<Check size={14}/>:<Cloud size={14}/>}<span>{saveStatus}</span></div><PresenceBar users={onlineUsers} currentUser={user}/><button className="cc-top-action" onClick={()=>setPanel({type:'activity'})}><Activity size={15}/></button><button className="cc-top-action" onClick={()=>setPanel({type:'copilot'})}><Bot size={15}/></button><button className="workspace-share" onClick={share}><Share2 size={15}/>Share</button><button className="workspace-members" onClick={()=>setMembersOpen(true)}><Users size={15}/>{members.length}</button><button className="workspace-more"><MoreHorizontal size={18}/></button><div className="workspace-avatar">{user?.name?.charAt(0).toUpperCase()}</div></div></header>
  <main className="workspace-editor"><div className="editor-stage"><CanvasToolbar activeTool={activeTool} setActiveTool={setActiveTool} onUndo={undo} onRedo={redo} onDelete={handleDelete} onDuplicate={handleDuplicate} onZoomIn={()=>setZoom(z=>Math.min(2,z+.1))} onZoomOut={()=>setZoom(z=>Math.max(.5,z-.1))} onResetZoom={()=>setZoom(1)} canUndo={historyIndexRef.current>0} canRedo={historyIndexRef.current<historyRef.current.length-1} canDelete={!!selectedObjectId} zoom={zoom} gridEnabled={gridEnabled} setGridEnabled={setGridEnabled} snapEnabled={snapEnabled} setSnapEnabled={setSnapEnabled}/><div className="editor-canvas-area"><Canvas objects={objects} selectedObjectId={selectedObjectId} activeTool={activeTool} zoom={zoom} gridEnabled={gridEnabled} snapEnabled={snapEnabled} onSelect={setSelectedObjectId} onObjectMove={handleMove} onObjectCreate={handleCreate} onObjectChange={handleChange} onCanvasClick={()=>activeTool==='select'&&setSelectedObjectId(null)} onCursorMove={cursorMove}/><CursorLayer cursors={remoteCursors}/><div className="canvas-zoom-indicator">{Math.round(zoom*100)}%</div><MiniMap objects={objects} zoom={zoom}/>{selectedObjectId&&<button className="cc-object-comment" onClick={addCommentPanel}><MessageCircle size={15}/><span>Comment</span></button>}</div><PropertiesPanel selectedObject={selectedObject} onChange={handleChange} onDelete={handleDelete} onDuplicate={handleDuplicate}/></div>
  <div className="editor-bottom-bar"><div className="bottom-left"><span className="shortcut-chip">V</span><span>{activeTool==='draw'?'Drag to draw freehand':'Drag objects to reposition'}</span><span className="bottom-divider"/><button className="cc-bottom-link" onClick={()=>setPanel({type:'history'})}><History size={13}/>History</button><button className="cc-bottom-link" onClick={addCommentPanel}><MessageCircle size={13}/>Comments {comments.filter(c=>!c.resolved).length||''}</button></div><div className="bottom-center"><button onClick={()=>setZoom(z=>Math.max(.5,z-.1))}>−</button><button className="bottom-zoom" onClick={()=>setZoom(1)}>{Math.round(zoom*100)}%</button><button onClick={()=>setZoom(z=>Math.min(2,z+.1))}>+</button></div><div className="bottom-right"><span>{objects.length} {objects.length===1?'object':'objects'}</span><span className="bottom-divider"/><span>{gridEnabled?'Grid on':'Grid off'}</span><span className="bottom-divider"/><button className="cc-export-mini" onClick={exportBoard}><Download size={13}/>Export</button></div></div></main>
  <CommandPalette open={commandOpen} onClose={()=>setCommandOpen(false)} onAction={commandAction}/>{panel&&<AdvancedPanel mode={panel} onClose={()=>setPanel(null)} documentId={document.id} objects={objects} comments={comments} setComments={setComments} versions={versions} setVersions={setVersions} workspace={workspace} members={members} activities={activities} onRestore={handleRestore}/>}<Modal open={membersOpen} onClose={()=>setMembersOpen(false)} title={`Members · ${workspace.name}`}><div className="members-list">{members.map(m=><div className="member-row" key={m.id}><div className="member-avatar">{m.name?.charAt(0).toUpperCase()}</div><div><strong>{m.name}</strong><span>{m.email}</span></div><em>{m.role}</em></div>)}</div></Modal>{shareOpen&&<div className="share-toast"><Copy size={15}/>Workspace link copied</div>}
 </div>;
}
