import { useContext, useState } from "react";
import { Link } from "react-router-dom";
import { ArrowLeft, Moon, Sun, Shield, User, LogOut } from "lucide-react";
import useAuth from "../../hooks/useAuth";
import { ThemeContext } from "../../context/ThemeContext";
import Avatar from "../../components/common/Avatar";
import "./Settings.css";

export default function Settings(){const {user,logout}=useAuth();const {theme,toggleTheme}=useContext(ThemeContext);const [saved,setSaved]=useState(false);return <main className="settings-page"><div className="settings-shell"><header className="settings-header"><Link to="/dashboard"><ArrowLeft size={17}/>Dashboard</Link><div><p>Account</p><h1>Settings</h1><span>Manage your profile and app preferences.</span></div></header><section className="settings-card"><div className="settings-card-head"><div className="settings-icon"><User size={18}/></div><div><h2>Profile</h2><p>Your authenticated account details.</p></div></div><div className="profile-settings"><Avatar name={user?.name} size="lg"/><div><strong>{user?.name}</strong><span>{user?.email}</span><small>Member since {user?.created_at?new Date(user.created_at).toLocaleDateString():"—"}</small></div></div></section><section className="settings-card"><div className="settings-card-head"><div className="settings-icon"><Moon size={18}/></div><div><h2>Appearance</h2><p>Choose how CollabCanvas looks on this device.</p></div></div><button className="theme-option" onClick={()=>{toggleTheme();setSaved(true);setTimeout(()=>setSaved(false),1200)}}>{theme==="dark"?<Moon size={18}/>:<Sun size={18}/>}<span><strong>{theme==="dark"?"Dark mode":"Light mode"}</strong><small>Stored locally for this browser.</small></span><b>{saved?"Saved":"Change"}</b></button></section><section className="settings-card"><div className="settings-card-head"><div className="settings-icon"><Shield size={18}/></div><div><h2>Security</h2><p>Your session uses a signed JWT and protected API requests.</p></div></div><div className="security-note">Never share your password or authentication token. Sign out when using a shared computer.</div></section><button className="logout-settings" onClick={()=>{logout();window.location.href="/login"}}><LogOut size={16}/>Sign out</button></div></main>}
